name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      flask:
        image: python:3.10
        ports:
          - 5000:5000
        options: --entrypoint=""
        volumes:
          - .:/app
        env: >
          bash -c "pip install -r /app/requirements.txt && python /app/main.py"

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Wait for Flask Server
        run: |
          for i in {1..10}; do
              curl -I localhost:5000 && break
              echo "Waiting for Flask Server to start..."
              sleep 1
          done

      - name: Run tests
        run: |
          pytest tests/
